apiVersion: v1
kind: Namespace
metadata:
  name: namespace-dev
  labels:
    name: ns-dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
  namespace: namespace-dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Crear deployment"
  name: deploymenttest-01
  namespace: namespace-dev
  labels:
    app: deptest-01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podtest-01
  template:
    metadata:
      labels:
        app: podtest-01
    spec:
      containers:
      - name: container-01
        image: nginx:alpine
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi