apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Se crea el deploymenttest-03 y el servicetest-02"
  name: deploymenttest-03
  labels:
    app: deptest-03
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podtest-02
  template:
    metadata:
      labels:
        app: podtest-02
    spec:
      containers:
      - name: container-02
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: servicetest-02
  labels:
    app: svctest-02
spec:
  type: NodePort
  selector:
    app: podtest-02
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80