apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      limits:
        memory: "200Gi"
      requests:
        memory: "100Gi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150G", "--vm-hang", "1"]