apiVersion: v1
kind: Namespace
metadata:
  name: namespace-dev
  labels:
    name: ns-dev
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-min-max-demo-lr
  namespace: namespace-dev
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 1
    defaultRequest:
      memory: 256Mi
      cpu: 500m
    type: Container
  - max:
      memory: 1Gi
      cpu: 1
    min:
      memory: 500Mi
      cpu: 500m
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest-01
  namespace: namespace-dev
  labels:
    app: podtest-01
spec:
  containers:
  - name: container-01
    image: nginx:alpine
    resources:
      limits:
        memory: 500Mi
        cpu: 1
      requests:
        memory: 400Mi
        cpu: 500m