apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-nginx
  labels:
    app: cfgm-nginx
data:
  nginx: |
    server {
      listen       80;
      server_name  localhost;
      
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }
      
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-env
  labels:
    app: cfgm-env
data:
  db_host: dev.host.local
  db_user: dev_user
  script: |
    echo El db host es: $DB_HOST y el db user es: $DB_USER > /usr/share/nginx/html/test.html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Change port to 90"
  name: deploymenttest-01
  labels:
    app: deptest-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podtest-01
  template:
    metadata:
      labels:
        app: podtest-01
    spec:
      containers:
        - name: container-01
          image: nginx:alpine
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap-env
                  key: db_host
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: configmap-env
                  key: db_user
          volumeMounts:
          - name: nginx-volume
            mountPath: /etc/nginx/conf.d
          - name: script-volume
            mountPath: /opt
      volumes:
        - name: nginx-volume
          configMap:
            name: configmap-nginx
            items:
            - key: nginx
              path: default.conf
        - name: script-volume
          configMap:
            name: configmap-env
            items:
            - key: script
              path: script.sh