apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-nginx
  labels:
    app: cfgm-test
data:
  test: 'Hello world'
  nginx: |
    server {
      listen       80;
      server_name  localhost;
      
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }
      
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Change port to 90"
  name: deploymenttest-01
  labels:
    app: deptest-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podtest-01
  template:
    metadata:
      labels:
        app: podtest-01
    spec:
      containers:
      - name: container-01
        image: nginx:alpine
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: config-volume
        configMap:
          name: configmap-nginx
          items:
          - key: nginx
            path: default.conf