apiVersion: v1
kind: Namespace
metadata:
  name: namespace-dev
  labels:
    name: namespace-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Se crean el Deployment para el namespace-dev"
  name: deploy-dev
  namespace: namespace-dev
  labels:
    app: deploy-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-dev
  template:
    metadata:
      labels:
        app: pod-dev
    spec:
      containers:
      - name: container-01
        imagePullPolicy: IfNotPresent
        image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: service-dev
  namespace: namespace-dev
  labels:
    app: service-dev
spec:
  type: NodePort
  selector:
    app: pod-dev
  ports:
    - protocol: TCP
      port: 80