apiVersion: v1
kind: ServiceAccount
metadata:
  name: myservice-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymenttest-01
  labels:
    app: deptest-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podtest-01
  template:
    metadata:
      labels:
        app: podtest-01
    spec:
      serviceAccountName: myservice-account
      containers:
      - name: container-01
        image: nginx:alpine
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: read-pods
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: myservice-account
  apiGroup: ""
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: pod-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io