apiVersion: v1
kind: ServiceAccount
metadata:
  name: myservice-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymenttest-01
  labels:
    app: deptest-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podtest-01
  template:
    metadata:
      labels:
        app: podtest-01
    spec:
      serviceAccountName: myservice-account
      containers:
      - name: container-01
        image: nginx:alpine