apiVersion: v1
kind: Pod
metadata:
  name: podtest-01
  labels:
    app: frontend
    env: dev
spec:
  containers:
  - name: container-01
    image: nginx:alpine
  - name: container-02
    image: postgres:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest-02
  labels:
    app: backend
    env: dev
spec:
  containers:
  - name: container-01
    image: nginx:alpine